name: PUBLISH

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: npm ci

      - name: Verify source
        run: npm run preversion

      - name: Build source
        run: npm run build

      - name: Publish packages to npm registry
        # Only publish public packages
        run: npm publish\
          --access public\
          --workspace packages/core/manifest\
          --workspace packages/core/react-loosely-lazy\
          --workspace packages/plugins/babel\
          --workspace packages/plugins/webpack
        env:
          NODE_AUTH_TOKEN: ${{secrets.REACT_LAZY_NPM_TOKEN}}
